# Generated by Django 6.0.6 on 2026-07-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('badge', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=100)),
                ('receiver_id', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('startup_age', models.IntegerField(blank=True, null=True)),
                ('funding_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('total_funding_usd', models.FloatField(blank=True, null=True)),
                ('team_size', models.IntegerField(blank=True, null=True)),
                ('monthly_revenue_usd', models.FloatField(blank=True, null=True)),
                ('annual_revenue_usd', models.FloatField(blank=True, null=True)),
                ('active_users', models.IntegerField(blank=True, null=True)),
                ('customer_growth_rate', models.FloatField(blank=True, null=True)),
                ('burn_rate', models.FloatField(blank=True, null=True)),
                ('runway_months', models.FloatField(blank=True, null=True)),
                ('valuation_usd', models.FloatField(blank=True, null=True)),
                ('business_model', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_competitors', models.IntegerField(blank=True, null=True)),
                ('market_size_usd', models.FloatField(blank=True, null=True)),
                ('market_growth_rate', models.FloatField(blank=True, null=True)),
                ('founder_experience_years', models.IntegerField(blank=True, null=True)),
                ('previous_startups', models.IntegerField(blank=True, null=True)),
                ('employee_growth_rate', models.FloatField(blank=True, null=True)),
                ('customer_retention_rate', models.FloatField(blank=True, null=True)),
                ('profitability', models.BooleanField(default=False)),
                ('startup_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('acquisition_status', models.CharField(blank=True, max_length=100, null=True)),
                ('ipo_status', models.CharField(blank=True, max_length=100, null=True)),
                ('success_label', models.CharField(blank=True, max_length=100, null=True)),
                ('startup_description', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('headquarters_city', models.CharField(blank=True, max_length=255, null=True)),
                ('headquarters_state', models.CharField(blank=True, max_length=255, null=True)),
                ('headquarters_country', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_round_date', models.CharField(blank=True, max_length=100, null=True)),
                ('top_investor', models.CharField(blank=True, max_length=255, null=True)),
                ('competitor_1', models.CharField(blank=True, max_length=255, null=True)),
                ('competitor_2', models.CharField(blank=True, max_length=255, null=True)),
                ('competitor_3', models.CharField(blank=True, max_length=255, null=True)),
                ('market_trend_score', models.IntegerField(blank=True, null=True)),
                ('innovation_score', models.IntegerField(blank=True, null=True)),
                ('investor_interest_score', models.IntegerField(blank=True, null=True)),
                ('technology_stack', models.CharField(blank=True, max_length=500, null=True)),
                ('target_audience', models.CharField(blank=True, max_length=500, null=True)),
                ('unique_selling_proposition', models.CharField(blank=True, max_length=500, null=True)),
                ('startup_stage_description', models.CharField(blank=True, max_length=500, null=True)),
                ('employee_count_last_year', models.IntegerField(blank=True, null=True)),
                ('monthly_active_users_last_year', models.IntegerField(blank=True, null=True)),
                ('customer_acquisition_cost_usd', models.FloatField(blank=True, null=True)),
                ('lifetime_value_usd', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('due', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
