# Generated by Django 6.0.6 on 2026-07-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255)),
                ('founder_name', models.CharField(max_length=255)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('success_score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=50)),
                ('startup_health', models.IntegerField()),
                ('investment_readiness', models.IntegerField()),
                ('executive_summary', models.TextField()),
                ('model_version', models.CharField(default='v1.0.0', max_length=50)),
                ('prediction_id', models.CharField(max_length=100, unique=True)),
                ('health_growth', models.IntegerField(default=50)),
                ('health_financial', models.IntegerField(default=50)),
                ('health_market', models.IntegerField(default=50)),
                ('health_team', models.IntegerField(default=50)),
                ('health_product', models.IntegerField(default=50)),
                ('strengths', models.TextField(default='[]')),
                ('weaknesses', models.TextField(default='[]')),
                ('recommendations', models.TextField(default='[]')),
                ('feature_importance', models.TextField(default='{}')),
            ],
        ),
    ]
