# Generated by Django 6.0.6 on 2026-07-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_predictionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
