# Generated by Django 6.0.6 on 2026-07-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_startup_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('investment_firm', models.CharField(max_length=255)),
                ('investor_type', models.CharField(choices=[('Angel Investor', 'Angel Investor'), ('Venture Capital', 'Venture Capital'), ('Corporate VC', 'Corporate VC'), ('Family Office', 'Family Office'), ('Accelerator', 'Accelerator'), ('Incubator', 'Incubator')], max_length=50)),
                ('firm_logo', models.URLField(blank=True, null=True)),
                ('short_description', models.TextField()),
                ('investment_thesis', models.TextField()),
                ('preferred_industries', models.JSONField(default=list)),
                ('preferred_startup_stages', models.JSONField(default=list)),
                ('preferred_funding_stages', models.JSONField(default=list)),
                ('preferred_business_models', models.JSONField(default=list)),
                ('preferred_locations', models.JSONField(default=list)),
                ('min_investment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('max_investment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('typical_check_size', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('portfolio_size', models.IntegerField(default=0)),
                ('portfolio_companies', models.TextField(blank=True, default='')),
                ('successful_exits', models.IntegerField(default=0)),
                ('total_investments', models.IntegerField(default=0)),
                ('website', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('application_url', models.URLField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
